app:
    resource: '@AppBundle/Controller/'
    type: annotation

registerpage:
      path:     /register/
      defaults: { _controller: AppBundle:Registry:register }
      methods:  [GET,POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

login:
      path:     /loginhome/
      defaults: { _controller: AppBundle:Home:login }
      methods:  [POST]

registerhome:
      path:     /registerhome/
      defaults: { _controller: AppBundle:Home:register }
      methods:  [POST]

homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
    methods:  [GET,POST]

dashboardpage:
    path:     /dashboard/
    defaults: { _controller: AppBundle:Dashboard:index }
    methods:  [GET, HEAD]

newpost:
      path:     /dashboard/newpost
      defaults: { _controller: AppBundle:Dashboard:newPost }
      methods:  [GET, POST]

test:
    path:     /test
    defaults: { _controller: AppBundle:test:index }
    methods:  [GET, POST]

showpost:
        path:      /post/{page}
        defaults:  { _controller: AppBundle:Dashboard:showpost }
        requirements:
            page: '\d+'

profilepage:
        path:      /profile/{page}
        defaults:  { _controller: AppBundle:Profile:index }
        requirements:
            page: '\d+'

newfollow:
        path:      /followto/
        defaults:  { _controller: AppBundle:Profile:newfollow }
        methods:  [GET, POST]