app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_registration_register:
     path:     /
     defaults: { _controller: AppBundle:Home:index }
     methods:  [GET,POST]

fos_user_registration_confirm:
      path:     /register/
      defaults: { _controller: AppBundle:Registry:register }
      methods:  [GET,POST]

fos_user_registration_check_email:
      path:     /register/
      defaults: { _controller: AppBundle:Registry:register }
      methods:  [GET,POST]

homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
    methods:  [GET]

dashboardpage:
    path:     /dashboard/
    defaults: { _controller: AppBundle:Dashboard:index }
    methods:  [GET, HEAD]

profilepage:
    path:     /profile/
    defaults: { _controller: AppBundle:Profile:index }
    methods:  [GET, HEAD]