app:
    resource: '@AppBundle/Controller/'
    type: annotation

registerpage:
      path:     /register/
      defaults: { _controller: AppBundle:Registry:register }
      methods:  [GET,POST]

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

login:
      path:     /loginhome/
      defaults: { _controller: AppBundle:Home:login }
      methods:  [POST]

registerhome:
      path:     /registerhome/
      defaults: { _controller: AppBundle:Home:register }
      methods:  [POST]

homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
    methods:  [GET,POST]

dashboardpage:
    path:     /dashboard/
    defaults: { _controller: AppBundle:Dashboard:index }
    methods:  [GET, HEAD]

newpost:
      path:     /dashboard/newpost
      defaults: { _controller: AppBundle:Dashboard:newPost }
      methods:  [POST]

deletepost:
      path:     /dashboard/deletepost
      defaults: { _controller: AppBundle:Dashboard:deletePost }
      methods:  [POST]

newquedada:
      path:     /dashboard/newquedada
      defaults: { _controller: AppBundle:Dashboard:newQuedada }
      methods:  [POST]

test:
    path:     /test
    defaults: { _controller: AppBundle:test:index }
    methods:  [GET, POST]

showpost:
        path:      /post/{page}
        defaults:  { _controller: AppBundle:Dashboard:showpost }
        requirements:
            page: '\d+'

joinevent:
        path:      /joinevent/
        defaults:  { _controller: AppBundle:Dashboard:joinEvent }
        methods:  [GET,POST]

unjoinevent:
        path:      /unjoinevent/
        defaults:  { _controller: AppBundle:Dashboard:unjoinEvent }
        methods:  [POST]

profilepage:
        path:      /profile/{page}
        defaults:  { _controller: AppBundle:Profile:index }
        requirements:
            page: '\d+'

newfollow:
        path:      /followto/
        defaults:  { _controller: AppBundle:Profile:newfollow }
        methods:  [POST]

unfollow:
        path:      /unfollow/
        defaults:  { _controller: AppBundle:Profile:unfollow }
        methods:  [POST]

joineventProfile:
        path:      /joineventprofile/
        defaults:  { _controller: AppBundle:Profile:joinEventProfile }
        methods:  [POST]

unjoineventProfile:
        path:      /unjoineventprofile/
        defaults:  { _controller: AppBundle:Profile:unjoinEventProfile }
        methods:  [POST]

coinspage:
        path: /coins/
        defaults: {_controller: AppBundle:Coins:index}
        methods: [GET,POST]