security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /
                failure_path: /
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                   path:   /logout
                   target: /
            anonymous: true

    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/*, role: ROLE_ADMIN }
        - { path: ^/dashboard/, role: ROLE_USER }
        - { path: ^/followto/, role: ROLE_ADMIN }
        - { path: ^/unfollow/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }