services:
 app.form.registration:
   class: AppBundle\Form\RegistrationType
   tags:
       - { name: form.type, alias: app_user_registration }

 app.form.login:
    class: AppBundle\Form\RegistrationType
    tags:
        - { name: form.type, alias: app_user_login }